### ISSUE TITLE
Preview Mode Not working

### ISSUE THREAD

**Issue by kevinparikh** [gtm-templates-simo-ahava/consent-mode#5]
@sahava - was using your consent mode tag available on GTM. For some reason when i update the consent setting to DENIED, the value in the preview mode still shows GRANTED, but works fine when i click the value within the tag. Not sure if this is a bug. 
<img width="556" alt="Screenshot 2024-02-04 at 9 25 41 PM" src="https://github.com/gtm-templates-simo-ahava/consent-mode/assets/158980472/3d797c41-7784-4eff-ab5f-630612c2f860">
<img width="952" alt="Screenshot 2024-02-04 at 9 26 11 PM" src="https://github.com/gtm-templates-simo-ahava/consent-mode/assets/158980472/829db2f4-af16-4199-a61e-1a90e9f96370">

**Comment by sahava** [comment]
Hi

You mean that some variable is returning the values as "granted" – that means the problem is with the variable or when it's evaluated. As I don't know what that variable is or how it works, you should probably take this up with whomever created that variable template.

Best way to ensure that consent mode works as it does is to use the "Consent" tab in Preview mode. That shows you what the current and updated state is at any given time.
